version: "3"

rpc:
  listen: ${RR_RPC_LISTEN:-tcp://127.0.0.1:6001}
  
status:
  address: ${RR_STATUS_ADDRESS:-127.0.0.1:2114}

server:
  command: "${RR_SERVER_COMMAND:-php app.php}"

http:
  address: ${RR_HTTP_ADDRESS:-0.0.0.0:8080}
  pool:
    debug: ${RR_POOL_DEBUG:-true}

logs:
  mode: ${RR_LOGS_MODE:-development}
  encoding: ${RR_LOGS_ENCODING:-console}
  level: ${RR_LOGS_LEVEL:-debug}