version: "3"

rpc:
  listen: tcp://127.0.0.1:6001

server:
  command: "php app.php"

http:
  address: 0.0.0.0:8080

# do not use development mode in production
logs:
  encoding: console
  level: debug
  mode: development